[build-system]
requires = [
    'setuptools >= 68.1.1',
    'pkgconfig',
    'cython >=3.0, != 3.0.3, <4.0',
    'cysignals >=1.10.2',
    'sagemath-environment',
]
build-backend = "setuptools.build_meta"
